
services:
  db_warehouse_test:
    container_name: db_warehouse_test
    image: postgres:14.4-alpine
    environment:
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: my_db
    ports:
      - "5438:5432"